server:
  port: 8092
integration:
  recipient:
    url: "http://${RECIPIENT_HOST:localhost}:8091/messages"
spring:
  rabbitmq.host : ${RABBITMQ_HOST:localhost}
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true