---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: microserviceLab
  labels:
    app: collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
        - name: collector
          image: microserviceLab/collector:release
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8092
          env:
            - name: RECIPIENT_HOST
              value: recipient-service
            - name: MESSAGES_DB_HOST
              value: postgres-service

---
apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: microserviceLab
  labels:
    app: collector
spec:
  selector:
    app: collector
  ports:
    - protocol: "TCP"
      port: 8092
      targetPort: 8092
  type: LoadBalancer
