server:
  port: 8091
spring:
  rabbitmq.host : ${RABBITMQ_HOST:localhost}
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: false
  endpoint:
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true