version: "3.4"
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - module2

networks:
  module2:
    ipam:
      driver: default